### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by gduncan3** [only2dhir/spring-boot-jwt#1]
Kindly commit your entire database schema if possible. Would like to see the relationships between User and Role tables.

**Comment by only2dhir** [comment]
Please find it here. - https://github.com/only2dhir/spring-security-jwt/blob/master/src/main/resources/query.sql  and the complete tutorial is here - [Spring security role base auth](https://www.devglan.com/spring-security/jwt-role-based-authorization)

**Comment by gduncan3** [comment]
Thanks. I just found it and closed the issue..but thanks again for the fast response
